minute = "րոպե"
day="Օր"
data="Տվյալ"
count="Քանակ"
total_days_str="Ընդհանուր 50 օր"
bought_a_pie="գնել է կարկանդակ"
days_bought_a_pie_str="օր գնել է կարկանդակ"
number_of_pie_bought_days="Կարկանդակ գնելու օրերի \\\\  քանակն  ընդհանուր օրերի "
part=" մասն է"

