january = "Հունվարի "
february = "Փետրվարի "
minute = "րոպե"
day="Օր"
time="Ժամանակ"
width="Լայնք"
average_time=" միջին ժամանակը (միջին թվաբանականը)"
mode="Մոդ"
data="Տվյալ"
count="Քանակ"
frequency_table="հաճախականային աղյուսակ"

