january = "January "
february = "February "
minute = " minutes"
day="Day"
time="Time"
width="width"
average_time="average time (arithmetic mean)"
mode="mode"
data_str="Data"
count="Count"
frequency_table_str="Frequency table"

