TASK_NUMBER_STR = "Խ. 11375"
TRAIN_LENGTH = r"280\text{մ}"

TRAIN_SPEED = r"72\text{ կմ/ժ}"

ONE_HOUR = r"1\text{ժ }"
KM = r"72\text{ կմ}"
TRAIN_CALCULATION = r"1\text{ժ = }60\text{ր = }60 \cdot 60\text{վ = }"
SECONDS = r"3600\text{ վ}"
METER = r"72 000\text{ մ}"
ONE_SECOND = r"1\text{ վ }"
QUESTION_MARK = r"\mathord{?}"
TRAIN_SPEED_TEXT = r"""\text{Գնացքը շարժվում է 20 մ/վ արագությամբ }"""
METER_SECOND = QUESTION_MARK + r"\text{ = 1 }\cdot \text{72000 : 3600 = 20 մ}"
RESULT_SECOND = r"\text{14}"
RESULT = r"\text{280 : 20 = 14 վ}"
