TASK_NUMBER_STR = "P. 11375"
TRAIN_LENGTH = r"280\text{m}"

TRAIN_SPEED = r"72\text{ km/h}"

ONE_HOUR = r"1\text{h }"
KM = r"72\text{ km}"
TRAIN_CALCULATION = r"1\text{h = }60\text{m = }60 \cdot 60\text{s = }"
SECONDS = r"3600\text{ s}"
METER = r"72 000\text{ m}"
ONE_SECOND = r"1\text{ s }"
QUESTION_MARK = r"\mathord{?}"
TRAIN_SPEED_TEXT = r"""\text{ The train is moving at a speed of 20 m/s }"""
METER_SECOND = QUESTION_MARK + r"\text{ = 1 }\cdot \text{72000 : 3600 = 20 m}"
RESULT_SECOND = r"\text{14}"
RESULT = r"\text{280 : 20 = 14 s}"
