task_number_string = "P․ 12189"
armen_string = "Armen"
vazgen_string = "Vazgen"
condition1_string = "Condition $1$` ", r"Vazgen collected $13$ mushrooms more \\ than Armen։"
condition2_string = "Condition $2$` ", r"Vazgen would have three times more than Armen, \\    if he collected $5$ more mushrooms"
