TASK_NUMBER_STR = "Խ. 12187"
CONDITION_1_0 = r"\text{Ամենափոքր բնական թիվը,  որի}"
CONDITION_1_1 = r"\text{թվանշանների գումարը 23 է}"
CONDITION_1_1_FINAL = r"\text{Թվանշանների գումարը 23 է}"
CONDITION_2 = r"\text{քիչ թվանշան = փոքր թիվ}"
CONDITION_3 = r"\text{Միանի՞շ}"
CONDITION_5 = r"\text{Երկնի՞շ}"
CONDITION_7 = r"\text{Եռանի՞շ}"
CONDITION_9 = r"\text{հնարավորին փոքր}"
CONDITION_10 = r"\text{հնարավորին մեծ}"
