TASK_NUMBER_STR = "Խ. 12187"
CONDITION_1_0 = r"\text{Ամենափոքր բնական թիվը,  որի}"
CONDITION_1_1 = r"\text{թվանշանների գումարը 23 է}"
CONDITION_1_1_FINAL = r"\text{Թվանշանների գումարը 23 է}"
CONDITION_2 = r"\text{քիչ թվանշան = փոքր թիվ}"
CONDITION_3 = r"\text{Միանի՞շ}"
CONDITION_4 = r"\text{1,2,3,4,5,6,7,8,9}"
CONDITION_5 = r"\text{Երկնի՞շ}"
CONDITION_6 = r"\text{9 + 9} < {23}"
CONDITION_7 = r"\text{Եռանի՞շ}"
CONDITION_8 = r"\text{9+9+9} > {23}"
PLUS = r"\text{ + }"
EQUAL_23 = r"\text{ = 23 }"
CONDITION_9 = r"\text{հնարավորին փոքր}"
CONDITION_10 = r"\text{հնարավորին մեծ}"
NINE = r"9"
SOLUTION_PART_1 = r"\text{23 - 9 - 9 = 5 }"
