TASK_NUMBER_STR = "P. 12187"
CONDITION_1_0 = r"\text{The smallest natural number whose}"
CONDITION_1_1 = r"\text{sum of digits is 23}"
CONDITION_1_1_FINAL = r"\text{Sum of digits is 23}"
CONDITION_2 = r"\text{less digits = smaller number}"
CONDITION_3 = r"\text{Single digit?}"
CONDITION_5 = r"\text{Two digits?}"
CONDITION_7 = r"\text{Three digits?}"
CONDITION_9 = r"\text{as small as possible}"
CONDITION_10 = r"\text{as large as possible}"
