TASK_NUMBER_STR = "Խ. 12187"
CONDITION_1_0 = r"\text{The smallest natural number whose}"
CONDITION_1_1 = r"\text{sum of digits is 23}"
CONDITION_1_1_FINAL = r"\text{Sum of digits is 23}"
CONDITION_2 = r"\text{less digit = small number}"
CONDITION_3 = r"\text{Single digit?}"
CONDITION_4 = r"\text{1,2,3,4,5,6,7,8,9}"
CONDITION_5 = r"\text{Two digits?}"
CONDITION_6 = r"\text{9 + 9} < {23}"
CONDITION_7 = r"\text{Three digits?}"
CONDITION_8 = r"\text{9+9+9} > {23}"
PLUS = r"\text{ + }"
EQUAL_23 = r"\text{ = 23 }"
CONDITION_9 = r"\text{as small as possible}"
CONDITION_10 = r"\text{as large as possible}"
NINE = r"9"
SOLUTION_PART_1 = r"\text{23 - 9 - 9 = 5 }"
