taskNumberString = "Խ. 12804"
problem_setting_1_part_1="Լիլիթը հանեց 4"
problem_setting_1_part_2="արդյունքը բազմապատկեց 5-ով"
problem_setting_2_part_1="Մարին հանեց 8"
problem_setting_2_part_2="արդյունքը բազմապատկեց 7-ով"
problem_setting_part3="Ստացվեց նույն արժեքը"
and_string=" և "
book_count_x="Գրքերի քանակը՝ $x$"
solution_str= "Պահարանում կա 18 գիրք"

