TASK_NUMBER_STR = "Խ. 12674"
LEFT_CAR_SPEAD = r"80\text{ կմ/ժ}"
RIGHT_CAR_SPEAD = r"70\text{ կմ/ժ}"
MEETING_MOMENT = r"\text{Հանդիպման պահը}"
BEFORE_MEETING_1 = r"\text{Հանդիպումից }"
BEFORE_MEETING_2 = r"\text{ րոպե առաջ}"
ONE_HOUR_ROAD = r"\text{ Մեքենայի մեկ ժամվա անցած ճանապարհ}"
KM_80 = r"80\text{կմ}"
KM_70 = r"70\text{կմ}"
PLUS = r"\text{+}"
EQUAL = r"\text{ = }"
KM_150 = r"\text{150կմ}"
