TASK_NUMBER_STR = "P. 12674"
LEFT_CAR_SPEAD = r"80\text{ km/h}"
RIGHT_CAR_SPEAD = r"70\text{ km/h}"
MEETING_MOMENT = r"\text{Meeting moment}"
BEFORE_MEETING_1 = r"\text{}"
BEFORE_MEETING_2 = r"\text{ minutes before the meeting}"
ONE_HOUR_ROAD = r"\text{ Car's pass distance in one hour}"
KM_80 = r"80\text{km}"
KM_70 = r"70\text{km}"
PLUS = r"\text{+}"
EQUAL = r"\text{ = }"
KM_150 = r"\text{150km}"
