task_number_string = "Խ. 10320"
Arsen_string = "Արսեն"
road_length_string = r"605\text{կմ}"
first_part_of_road_time_string = r"4\text{ժ}"
second_part_of_road_time_string = r"3\text{ժ}"
segment_15_string = "15"
