task_number_string = "P. 10320"
Arsen_string = "Arsen"
road_length_string = r"605\text{km}"
first_part_of_road_time_string = r"4\text{h}"
second_part_of_road_time_string = r"3\text{h}"
segment_15_string = "15"
hour_string = r"\text{h}"
km = r"\text{km}"
