TASK_NUMBER_STR = "P. 12699"
CONDITION_1_0 = r"\text{On the 1st day}"
CONDITION_2_0 = r"\text{On the 2nd day}"
PART = r"\text{part}"
CONDITION_3 = r"\text{25 pages left}"
BRACE_TEXT_1 = r"\frac{1}{3} \text{ part}"
BRACE_TEXT_2 = r"\frac{1}{4} \text{ part}"
PAGES_25 = r"\text{25 pages }"
SOLUTION_PART_4 = r"\text{The whole = 25 : } \frac{5}{12} \text{ = 25}\cdot \frac{12}{5}"
RESULT = r"\text{ 60 pages}"
BRACE_TEXT_3 = r"\text{ 12 equal parts}"
PART_4 = r"\text{ 4 part}"
PART_3 = r"\text{ 3 part}"
PART_5 = r"\text{ 5 part}"
