TASK_NUMBER_STR = "Խ. 12695"
A = r"A"
B = r"B"
CONDITION_1 = r"\text{Անցավ ճանապարհի 2/5 մասը}"
CONDITION_2 = r"\text{Մնաց գնալու 126 կմ}"
TWO_FIFTH_OF_ROAD = r"\text{ճանապարհի 2/5 մասը}"
KM_126 = r"\text{126 կմ}"
NUM_1 = r"1\text{}"
NUM_2 = r"2\text{}"
NUM_3 = r"3\text{}"
SOLUTION_PART_1= r"\text{3 մասը = 126 կմ}"
SOLUTION_PART_2 = r"\text{1 մասը = 126 : 3 = \thinspace \thinspace \thinspace 42 կմ}"
SOLUTION_PART_3 = r"\text{Ամբողջ ճանապարհը = \: 5} \cdot \text{42 \thinspace  = 210 կմ}"
