TASK_NUMBER_STR = "P. 12695"
A = r"A"
B = r"B"
CONDITION_1 = r"\text{Passed 2/5 of the road}"
CONDITION_2 = r"\text{126 km left to go}"
TWO_FIFTH_OF_ROAD = r"\text{2/5 of the road}"
KM_126 = r"\text{126 km}"
NUM_1 = r"1"
NUM_2 = r"2"
NUM_3 = r"3"
SOLUTION_PART_1= r"\text{3 parts = 126 km}"
SOLUTION_PART_2 = r"\text{1 part = 126 : 3 = \thinspace \thinspace \thinspace 42 km}"
SOLUTION_PART_3 = r"\text{The whole road = \: 5} \cdot \text{42 \thinspace  = 210 km}"
