TASK_NUMBER_STR = "Խ. 10938"
SECONDS_18 = r"18\text{ վ}"
TRAIN_LENGTH = r"24\text{մ}"
BRIDGE_LENGTH = r"48\text{մ}"
PLUS = r"\text{+}"
METERS_72 = r"72\text{մ}"
ONE_SECOND = r"1\text{ վ }"
DIVIDE = r"\text{ : }"
METER_SECOND_4 = r"4\text{ մ/վ }"
EQUAL = r"\text{ = }"
RESULT = r"\text{ 6 վ }"
BRIDGE_LENGTH_TEXT = r"\text{ Կամուրջ 48 մ}"
TRAIN_LENGTH_TEXT = r"\text{Գնացք 24 մ }"
