TASK_NUMBER_STR = "P. 10938"
SECONDS_18 = r"18\text{ s}"
TRAIN_LENGTH = r"24\text{m}"
BRIDGE_LENGTH = r"48\text{m}"
PLUS = r"\text{+}"
METERS_72 = r"72\text{m}"
ONE_SECOND = r"1\text{ s }"
DIVIDE = r"\text{ : }"
METER_SECOND_4 = r"4\text{ m/s }"
EQUAL = r"\text{ = }"
RESULT = r"\text{ 6 s }"
BRIDGE_LENGTH_TEXT = r"\text{ Bridge 48 m}"
TRAIN_LENGTH_TEXT = r"\text{Train 24 m }"
