tuskNameString = "գծային ֆունկցիայի գրաֆիկը"
linear_function_str = "Գծային ֆունկցիա"
passes_through_point = "անցնում է $(0, 3)$ կետով"
is_parallel_to_line = "ուղիղը զուգահեռ է $y=2x –$ ին"
is_parallel_to_line_and_passes_through_point = " ուղիղը զուգահեռ է $y=2x$ ուղղին \\\\ և անցնում է $(0,3)$ կետով"
