tuskNameString = "the graph of a linear function"
linear_function_str = "Linear function"
passes_through_point = "passes through the point $(0, 3)$"
is_parallel_to_line = "is parallel to line $y=2x$"
is_parallel_to_line_and_passes_through_point = " is parallel to line $y=2x$ \\\\ and passes through point $(0, 3)$"
