task_number_string = "Խ. 10349"
souren_string = "Սուրեն"
arshak_string = "Արշակ"
road_len = 430
meeting_time_string = r"15:00"
souren_time_string = r"10:00"
arshak_time_string = r"12:00"
road_length_string = str(road_len) + r"\text{կմ}"
souren_road_time_string = r"5\text{ժ}"
arshak_road_time_string = r"3\text{ժ}"
souren_recap_s_string = r"S=250\text{կմ}"
arshak_recap_s_string = r"S=180\text{կմ}"
souren_recap_v_string = r"V=50\text{կմ/ժ}"
arshak_recap_v_string = r"V=60\text{կմ/ժ}"
souren_recap_t_string = r"t=5\text{ժ}"
arshak_recap_t_string = r"V=3\text{ժ}"
condition1_string = "Պայման $1$՝ ", "Արշակը շարժվել է Սուրենից 10կմ/ժ ավելի մեծ արագությամբ։"
condition2_string = "Պայման $2$՝ ", "Սուրենը ճանապարհ է ընկել 10:00 ու տեղ հասել 15:00:"
condition3_string = "Պայման $3$՝ ", "Արշակը սկսել է ճամփորդել 12:00 և տեղ է հասել 15:00:"
condition4_string = "Պայման $4$՝ ", "Ընդհանուր ճանապարհը 430կմ է։"
segment_10_string = "10"
hour_string = r"\text{ժ}"
question_mark_string = r"?"
km = r"\text{կմ}"
