TASK_NUMBER_STR = "Խ. 11946"
A = r"A"
B = r"B"
CONDITION_1 = r"\text{1. ամբողջ ճանապարհը կարող է անցնել 21 ժամում։}"
CONDITION_2_1 = r"\text{2. 1/3 մասն անցնելուց հետո արագությունը}"
CONDITION_2_2 = r"\text{նվազեցրեց 30\%–ով։}"
HOUR_21 = r"\text{21 ժամ}"
FLAG_POINT_TEXT = r"\text{1/3}"
ROAD_FIRST_PART_TEXT = r"\text{21} \cdot \text{1/3 = 7 ժամ}"
ROAD_SECOND_PART_TEXT = r"\text{21 - 7 = 14 ժամ}"
ROAD_SECOND_PART_TEXT_PERCENT = r"\text{30\% դանդաղ}"
CONDITION_3 = r"\text{30\%-ով դանդաղ = նույն ժամանակում 30\%-ով քիչ}"
SOLUTION_1_PART = r"\text{14 ժամ } \rightarrow \text{ 70\%}"
SOLUTION_2_PART = r"\mathord{?} \text{ ժամ} \rightarrow \text{100\%}"
SOLUTION_3_PART = r"\text{ 14 } \cdot \text{100 / 70 = 20 ժ}"
HOUR_7 = r"7\text{ ժամ}"
HOUR_14 = r"14\text{ ժամ}"
HOUR = r"\text{ ժամ}"
PLUS = r"\text{ + }"
SOLUTION_RESULT = r"\text{  = 27 ժամ}"
PERCENT_100 = r"\text{100\%}"
PERCENT_70 = r"\text{70\%}"
