TASK_NUMBER_STR = "Խ. 11946"
A = r"A"
B = r"B"
CONDITION_1 = r"\text{1. the whole way can be passed in 21 hours.}"
CONDITION_2_1 = r"\text{2. After passing 1/3 of the way, he reduced}"
CONDITION_2_2 = r"\text{the speed by 30%.}"
HOUR_21 = r"\text{21 hours}"
FLAG_POINT_TEXT = r"\text{1/3}"
ROAD_FIRST_PART_TEXT = r"\text{21} \cdot \text{1/3 = 7 hours}"
ROAD_SECOND_PART_TEXT = r"\text{21 - 7 = 14 hours}"
ROAD_SECOND_PART_TEXT_PERCENT = r"\text{30\% slower}"
CONDITION_3 = r"\text{30\% slower = 30\% less simultaneously}"
SOLUTION_1_PART = r"\text{14 hours } \rightarrow \text{ 70\%}"
SOLUTION_2_PART = r"\mathord{?} \text{ hours} \rightarrow \text{100\%}"
SOLUTION_3_PART = r"\text{ 14 } \cdot \text{100 / 70 = 20 h}"
HOUR_7 = r"7\text{ hours}"
HOUR_14 = r"14\text{ hours}"
HOUR = r"\text{ hours}"
PLUS = r"\text{ + }"
SOLUTION_RESULT = r"\text{  = 27 hours}"
PERCENT_100 = r"\text{100\%}"
PERCENT_70 = r"\text{70\%}"
