name: Check existing videos

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: sudo apt install libcairo2-dev libpango1.0-dev ffmpeg texlive-latex-recommended texlive-science texlive-xetex texlive-fonts-extra texlive tipa
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
      - name: Rendering Scenes
        run: PYTHONPATH=lib:objects python qarakusi.am.py 10107 -pql
